# Generated by Django 5.1.7 on 2025-03-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='current_cycle_hours',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='current_cycle_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(max_length=100),
        ),
    ]
