# Generated by Django 5.1.7 on 2025-03-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_current_latitude_trip_current_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used',
            field=models.PositiveIntegerField(),
        ),
    ]
