# Generated by Django 5.1.7 on 2025-03-15 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_eldlog_created_at_eldlog_log_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eldlog',
            name='log_end_time',
        ),
        migrations.RemoveField(
            model_name='eldlog',
            name='log_start_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='estimated_end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.AddField(
            model_name='eldlog',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
